# Generated by Django 3.2.4 on 2021-08-04 06:57

import django.core.validators
from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('first_name', models.CharField(max_length=12)),
                ('last_name', models.CharField(max_length=20)),
                ('age', models.PositiveSmallIntegerField()),
                ('date_of_birth', models.DateField(null=True)),
                ('nationlity', models.CharField(choices=[('Kenyan', 'Kenyan'), ('Ugandan', 'Ugandan'), ('Rwandan', 'Rwandan'), ('South Sudanese', 'South Sudanese')], default='Kenyan', max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Non-Binary', 'Non-Binary'), ('Transgender', 'Transgender')], default='Female', max_length=12)),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phoneNumber', models.CharField(max_length=16, null=True)),
                ('medicalReport', models.FileField(null=True, upload_to='documents/%y/%m/%d')),
                ('admissionDate', models.DateField(default='dd-mm-yyyy')),
                ('academic_year', models.PositiveIntegerField(default=2021, validators=[django.core.validators.MinValueValidator(1984), student.models.max_value_current_year])),
                ('city', models.CharField(choices=[('Nairobi', 'Nairobi'), ('Kampala', 'Kampala'), ('Kigali', 'Kigali'), ('kartum', 'Kartum')], default='Nairobi', max_length=12)),
                ('guadian_name', models.CharField(max_length=20, null=True)),
                ('guadian_phoneNumber', models.CharField(max_length=16, null=True)),
                ('profile_picture', models.ImageField(null=True, upload_to='images|')),
            ],
        ),
    ]
