# Generated by Django 3.2.4 on 2021-08-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('first_name', models.CharField(max_length=12)),
                ('last_name', models.CharField(max_length=20)),
                ('nationlity', models.CharField(choices=[('Kenyan', 'Kenyan'), ('Ugandan', 'Ugandan'), ('Rwandan', 'Rwandan'), ('South Sudanese', 'South Sudanese')], default='Kenyan', max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Non-Binary', 'Non-Binary'), ('Transgender', 'Transgender')], default='Male', max_length=12)),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phoneNumber', models.CharField(max_length=16, null=True)),
                ('course', models.CharField(max_length=20)),
                ('contarct', models.FileField(null=True, upload_to='documents/%y/%m/%d')),
                ('Resume', models.FileField(null=True, upload_to='documents/%y/%m/%d')),
                ('Salary', models.PositiveBigIntegerField()),
                ('Company', models.CharField(max_length=20)),
                ('profile_picture', models.ImageField(null=True, upload_to='images|')),
            ],
        ),
    ]
