# Generated by Django 3.2.4 on 2021-08-07 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='contarct',
            new_name='contract',
        ),
    ]
